"""add study_plans table

Revision ID: 719c6e19e17a
Revises: d41d6550e524
Create Date: 2026-03-03 16:14:15.661725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719c6e19e17a'
down_revision: Union[str, None] = 'd41d6550e524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_text', sa.Text(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_plans_plan_date', 'study_plans', ['plan_date'], unique=False)
    op.create_index('ix_study_plans_user_id', 'study_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_study_plans_user_id', table_name='study_plans')
    op.drop_index('ix_study_plans_plan_date', table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
